GET http://localhost:3001/api/info/
###
GET http://localhost:3001/api/persons/
###
GET http://localhost:3001/api/persons/68d05416983d6c9ff6e9cd0d
###
DELETE http://localhost:3001/api/persons/68d05416983d6c9ff6e9cd0d
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Marko",
    "number": "123-12-312"
}

